name: phpstan

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          tools: composer:v2
      - run: composer install --prefer-dist --no-interaction --no-suggest
      - run: composer phpstan

